baseURL = "http://discordrpg.com/"
languageCode = "en-us"
title = "Discord RPG Bot"
theme = "hugo-book"
googleAnalytics = "G-YMEW5BY03V"

[build]
  command = "hugo --gc --minify"


[[menu.main]]
  identifier = "docs"
  name = "docs"
  title = "docs"
  url = "/"
  weight = 10

[context.production.environment]
  HUGO_VERSION = "0.91.2"
  HUGO_ENV = "production"

[params]
  BookTheme = 'dark'
