baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Discord RPG Bot'
theme = "hugo-book"

[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.91.2"
  HUGO_ENV = "production"

[params]
  BookTheme = 'dark'
